### PR TITLE
[ColsSelector] renamed the directory path to match the controllers name

### PR DESCRIPTION
**Pull request by markussc**
If approved, please create a new release of the bundle

### CODE REVIEW

**Comment by markussc** [comment]
@SimonHeimberg what do you propose? Should we rename everything to "ColsSelector" or to "ColumnSelector" ? I think the effort will be the same in the end.

**Comment by SimonHeimberg** [comment]
What is the reason? Style? Functionality?

If possible, compatibility should be kept.

**Comment by markussc** [comment]
the reason is simply that it does not work in CUBE TM as it is today. The twig files are not found by the controller action.

**Comment by SimonHeimberg** [comment]
❓ But it works when I go to http://hesi.dev.cubetools.ch/tm/app_dev.php/execution/testrun/ (running on 3.8.7-177-gd4b9e4e d4b9e4e and 3.8.7-177-gd4b9e4e d4b9e4e )

**Comment by SimonHeimberg** [comment]
Renaming the Controller is better, because the macros are used form external.

Still interested when it does not work. This is always an excellent reason for a change.

**Pull request merged**
